logging.level:
  com.pivotal: debug
  #  org.springframework: debug
  org.icgc.argo: debug

server.port: 8086

gatekeeper.url: "http://localhost:8080/graphql"

rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      port: 5672
      username: user
      password: pass

scheduler.consumer:
  queue: "scheduler-queue"
  topicExchange: "gatekeeper-out"
  bufferDurationSec: 10
scheduler.producer:
  topicExchange: "gatekeeper-in"

scheduler:
  workDirTemplate: "<SCHEDULED_DIR>"
  maxCostPerDir: 3
  dirValues:
    - "nfs-local/nfs-1"
    - "nfs-local/nfs-2"
  workflows:
    - url: "https:///hello"
      name: "hello"
      maxTotalRuns: 2
      cost: 2
    - url: "http://sanger-wgs"
      name: "sanger-wgs"
      maxTotalRuns: 4
      cost: 1
